version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app/app
      - model-cache:/root/.cache/huggingface
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - MODEL_TYPE=${MODEL_TYPE:-qwen}
      - QWEN_MODEL_NAME=${QWEN_MODEL_NAME:-Qwen/Qwen2.5-Omni-7B}
      - Phi_MODEL_NAME=${PHI_MODEL_NAME:-microsoft/Phi-4-multimodal-instruct}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ipc: host
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - api
    restart: unless-stopped

volumes:
  model-cache:
